version: '3.9'

services:
  realestate-properties-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:922;http://+:881
      - ASPNETCORE_HTTPS_PORTS=30903
      - ASPNETCORE_HTTP_PORTS=30902
      - PROCESS_TYPE=docker-compose
    ports:
      - "30903:922"
      - "30902:881"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
