version: '3.9'

networks:
  realestate-properties-network:
  # default:
  #   name: realestate-properties-network

services:
  realestate-properties-api:
    image: ${DOCKER_REGISTRY-}realestatepropertiesapi
    container_name: realestate-properties-API
    build:
      context: .
      dockerfile: RealEstateProperties.API/Dockerfile
    depends_on:
      - realestate-properties-db
    networks:
      - realestate-properties-network

  realestate-properties-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: realestate-properties-DB
    hostname: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_USER=sa
      - MSSQL_SA_PASSWORD=RealEstateProperties__Password
    ports:
      - 7165:1433
    expose:
      - 7165
    volumes:
      - realestate-properties-db:/var/opt/mssql
    networks:
      - realestate-properties-network

volumes:
  realestate-properties-db:
